apply plugin: 'com.android.library'

android {
    compileSdkVersion 36
    namespace 'org.opencv'

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 34
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }
}