apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    namespace 'org.opencv'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
    }

    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            java.srcDirs = ['java/src']
            aidl.srcDirs = ['java/src']
            res.srcDirs = ['java/res']
            manifest.srcFile 'java/AndroidManifest.xml'
            jniLibs.srcDirs = ['native/libs']
        }
    }

    packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libopencv_java4.so'
        pickFirst 'lib/armeabi-v7a/libopencv_java4.so'
    }
}

task copyNativeLibs(type: Copy) {
    from 'native/libs'
    into 'src/main/jniLibs'
    include '**/*.so'
}